### ISSUE TITLE
Invalid characters in URIs of NUTS codes

### ISSUE THREAD

**Issue by jindrichmynarz** [opendatacz/VVZ_extractor#1]
The extractor produces invalid characters in URIs of NUTS codes, such as the following:

```
<contract> pceu:hasParentRegion <http://ec.europa.eu/eurostat/ramon/rdfdata/nuts2008/CZ 080> .
```

A solution might consist of removing all white-space from strings used in NUTS URIs. In general, every string used as a part of URI should be URI-escaped using [`encode-for-uri`](http://www.w3.org/TR/xpath-functions/#func-encode-for-uri).

**Comment by michalpomykacz** [comment]
Fixed in XSLT and in dataset (graph http://linked.opendata.cz/resource/dataset/vestnikverejnychzakazek.cz
